Allow --verbose for server mode
quil-lang/quilc pull request #682
Opened 2020-11-25 22:00 UTC by notmgsk

2021-03-11 18:50 UTC, stylewarning commented
Print a warning that `--verbose` is not really appropriate for multithreaded server environments at the top of quilc startup output (in server mode only).

2021-03-25 18:24 UTC, stylewarning requested changes
just this and looks GTM

2021-03-25 18:24 UTC, stylewarning commented on app/src/entry-point.lisp
> +                                :verbose (when verbose *human-readable-stream*)
please use `if` with explicit else-branch

2021-04-01 13:47 UTC, notmgsk commented on app/src/entry-point.lisp
> +                                :verbose (when verbose *human-readable-stream*)
donezo

2021-04-01 18:43 UTC, stylewarning approved these changes

2021-04-01 18:43 UTC, stylewarning commented on app/src/entry-point.lisp
> +           (warn "--verbose output is not appropriate for production multithreaded environments, and should b used when debugging and with care"))
I'm not going to hold this PR up but WARN takes a format string so you

```
"can break lines ~
 like this."
```

2021-05-13 17:58 UTC, merged