refactor chip-contiguous-subschedule-from-last-instructions to non-re…
quil-lang/quilc pull request #693
Opened 2021-01-26 03:02 UTC by erichulburd

…cursive

2021-01-26 03:09 UTC, erichulburd reviewed
Lisp single-link lists are still not entirely intuitive to me, so want to double check myself on the append and setf/cdr operation below.

Also, any reason to use setq in place of setf here or just generally?

2021-01-26 03:09 UTC, erichulburd commented on src/addresser/outgoing-schedule.lisp
> +  ;;       change SORT'xs KEY to grab that value, then strip the cells away at end.
clean

2021-01-26 03:09 UTC, erichulburd commented on src/addresser/outgoing-schedule.lisp
> +               (progn
clean

2021-01-26 03:09 UTC, erichulburd commented on src/addresser/outgoing-schedule.lisp
> +                          (setf queue (append queue (list predecessor)))))
Is this operation efficient memory resource-wise?

2021-01-26 03:09 UTC, erichulburd commented on src/addresser/outgoing-schedule.lisp
> +               (setq leaves (cdr leaves))
Is this operation efficient memory resource-wise?

2021-01-26 11:12 UTC, stylewarning requested changes
I noted mostly style and efficiency concerns, which you may incorporate. After that, I'll be happy to check correctness.

2021-01-26 11:12 UTC, stylewarning commented on src/addresser/outgoing-schedule.lisp
> +                          (setf queue (append queue (list predecessor)))))
Generally, no. It will copy the entire `queue`, and as a part of that copy, append the element. So it's O(N) in time and space. It's preferred to use an actual queue-like data structure instead of raw Lisp lists.

There are a couple options for FIFO queues in quilc. The first is to use `cl-heap`. The second is to use the very simple queue data structure in `god-table.lisp` (see `cl-quil.clifford::make-queue`).

2021-01-26 11:12 UTC, stylewarning commented on src/addresser/outgoing-schedule.lisp
> +    (loop while queue
style: `:while` and `:do` in LOOP

style: write

```
(loop :while queue :do 
  ...)
```

2021-01-26 11:12 UTC, stylewarning commented on src/addresser/outgoing-schedule.lisp
> +          do (let* (
don't put parens on their own line

2021-01-26 11:12 UTC, stylewarning commented on src/addresser/outgoing-schedule.lisp
> +               (setf queue (cdr queue))
this can be shorted to just `(pop queue)`

2021-01-26 11:12 UTC, stylewarning commented on src/addresser/outgoing-schedule.lisp
> +                          (setf queue (append queue (list predecessor)))))
If you instead just want a _stack_, then using `push` and `pop` on Lisp lists works fine, and is O(1). (I don't think a stack can be used for this BFS though.)

2021-01-26 11:12 UTC, stylewarning commented on src/addresser/outgoing-schedule.lisp
> +               (loop for predecessor in predecessors
style: use `:for` and `:in`

or better, just use `dolist` instead of `loop`:

```
(dolist (predecessor predecessors)
  ...)
```

2021-01-26 11:12 UTC, stylewarning commented on src/addresser/outgoing-schedule.lisp
> +                          (setf queue (append queue (list predecessor)))))
style: close all trailing parens on a single line

2021-01-26 11:12 UTC, stylewarning commented on src/addresser/outgoing-schedule.lisp
> +  "mark-predecessors-seen performs a breadth first search on instr as the root node and marks all of its descendants as true in hash-table seen."
style: No need to restate the function name in the doc string.

style: Capitalize argument names:  `Performs a breadth-first search on INSTR as the root node ... hash-table SEEN."

2021-01-26 11:12 UTC, stylewarning commented on src/addresser/outgoing-schedule.lisp
> +               (setq leaves (cdr leaves))
Yes, it's O(1). And you can alternatively write:

```
(pop leaves)
```

or if you want to set `instr` and `leaves` at the same time, you can instead do:

```
(destructuring-bind (instr . leaves) leaves
  ...)
```

2021-01-26 11:12 UTC, stylewarning commented on src/addresser/outgoing-schedule.lisp
> +                    (mark-predecessors-seen instr earlier-instrs seen)
style: trail all parens on one line

2021-01-26 11:12 UTC, stylewarning commented on src/addresser/outgoing-schedule.lisp
> +                    (setf leaves (append leaves (reverse (gethash instr earlier-instrs)))))
Beware, this will be `O(size(leaves) + size(hash-value))` in time and space

2021-01-26 21:58 UTC, erichulburd reviewed
Per discussion with Mark, I also owe a new test case that passes here but will blow up on the previous implementation.

2021-01-26 21:58 UTC, erichulburd commented on src/addresser/outgoing-schedule.lisp
> +  "performs a depth first search on INSTR as the root node and marks all of its descendants as true in hash-table SEEN."
I elected here to perform a DFS rather than BFS to make use of native list... _Not sure_ if BFS vs DFS matters here because this is an exhaustive search that has to visit all of the nodes.

2021-01-26 21:58 UTC, erichulburd commented on src/addresser/outgoing-schedule.lisp
> +               (push earlier-instr leaves)))
`leaves` is a copy of the `lscheduler-last-instrs` so mutation is ok here - my assumption throughout these changes is that `push` and `pop` are constant time operations. If that's not the case, then I need to re-think this again.

2021-01-26 21:58 UTC, erichulburd commented on src/addresser/outgoing-schedule.lisp
> +      (let ((instr (pop leaves)))
This outer loop assumes a DFS as well which is necessary for the algorithm to run correctly. EG see last test case in ` test-fidelity-addresser-subschedule`.

2021-01-27 19:37 UTC, erichulburd commented on tests/addresser-tests.lisp
> +         (circuit-depth 99999))
This spec runs locally in 1.35s, pretty slow. Should I move it to benchmarks?

2021-01-27 19:39 UTC, erichulburd commented on tests/addresser-tests.lisp
> +(deftest test-fidelity-addresser-subschedule-on-deep-circuit ()
Can confirm this spec will result in control stack exhaustion with old implementation:

![Screen Shot 2021-01-27 at 11 32 38 AM (2)](https://user-images.githubusercontent.com/3526083/106044147-3117c600-6094-11eb-9d7f-97b59a0df200.png)

2021-01-27 19:40 UTC, notmgsk commented on tests/addresser-tests.lisp
> +         (circuit-depth 99999))
I think this is probably excessive. In a quick test I was able to trigger the problem with ~5000 instructions.

2021-01-27 20:07 UTC, notmgsk commented
FYI it looks like `chip-schedule-from-carving-point` is unused now, and can probably be removed.

2021-01-27 21:51 UTC, notmgsk requested changes

2021-01-28 01:38 UTC, erichulburd commented on src/addresser/outgoing-schedule.lisp
> -             (bottoms-up (instr)
🍻

2021-01-28 01:41 UTC, erichulburd commented on tests/addresser-tests.lisp
> +(deftest test-fidelity-addresser-subschedule-on-deep-circuit ()
All I really care about is ENORMOUS FONT. Otherwise, I'm open.

2021-04-01 14:46 UTC, notmgsk approved these changes

2021-04-01 18:50 UTC, stylewarning requested changes
My comments are consistency-in-style nits. Otherwise looks good-to-go.

2021-04-01 18:50 UTC, stylewarning commented on src/addresser/outgoing-schedule.lisp
> +  (let ((queue (list instr)))
nitpick, this is a stack, not a queue

2021-04-01 18:50 UTC, stylewarning commented on src/addresser/outgoing-schedule.lisp
> +      (let* ((predecessors (gethash (pop queue) earlier-instrs)))
`let` not `let*`

(`let*` isn't wrong, but not needed)

2021-04-01 18:50 UTC, stylewarning commented on src/addresser/outgoing-schedule.lisp
> +        (loop :for predecessor :in predecessors :do
use
```
(dolist (predecessor predecessors
  ...)
```

General QUILC policy is to use the `do*` form if possible

2021-04-01 18:50 UTC, stylewarning commented on src/addresser/outgoing-schedule.lisp
> +             (loop :for earlier-instr :in (gethash instr earlier-instrs) :do
`dolist`

2021-04-13 00:34 UTC, erichulburd commented
[test error](https://github.com/rigetti/quilc/pull/693/checks?check_run_id=2328917959#step:3:1293)

```
   When attempting to read the slot's value (slot-value), the slot
  COMPILATION-TOLERANCE is missing from the object
  #<CL-QUIL::STATE-PREP-COMPRESSION-TOLERANCE-ERROR {100560AB83}>.
It has a slot CL-QUIL::COMPILATION-TOLERANCE, while CL-QUIL-TESTS::COMPILATION-TOLERANCE is requested.
```

2021-04-15 21:14 UTC, stylewarning commented
> [test error](https://github.com/rigetti/quilc/pull/693/checks?check_run_id=2328917959#step:3:1293)
> 
> ```
>    When attempting to read the slot's value (slot-value), the slot
>   COMPILATION-TOLERANCE is missing from the object
>   #<CL-QUIL::STATE-PREP-COMPRESSION-TOLERANCE-ERROR {100560AB83}>.
> It has a slot CL-QUIL::COMPILATION-TOLERANCE, while CL-QUIL-TESTS::COMPILATION-TOLERANCE is requested.
> ```

Seems like a simple package issue, somewhere there's a `(slot-value foo 'compilation-tolerance)` that ought to be `(slot-value foo 'cl-quil::compilation-tolerance)`. (could also be `with-slots`)

2022-01-06 19:40 UTC, closed without merging