Add a chip builder DSL
quil-lang/quilc pull request #698
Opened 2021-01-28 15:37 UTC by notmgsk

Cribbed from the docstr:

Build a CHIP-SPECIFICATION from the provided ISA.

ISA is of the form

```
    (qcomplex
     (instruction-constructor
      instruction-constructor
      ...
     ))
```

where qcomplex is either a number indicating a qubit, or a pair of qubits (separated by a hyphen) indicating an edge between qubits. The instruction-constructor are functions that return a HASH-TABLE representing gate information for the qcomplex. For example, to build a 2Q chip with standard 1Q instructions and a CZ

```
    (chip "humber road chippy"
      (0
       (measure _ :fidelity 0.999)
       (rz _ _ :fidelity 0.99)
       (rx pi _ :fidelity 0.98)
       (rx -pi _ :fidelity 0.98)
       (rx pi/2 _ :fidelity 0.98)
       (rx -pi/2 _ :fidelity 0.98)
       (rx pi _ :fidelity 0.98))
      (1
       (measure _ :fidelity 0.999)
       (rz _ _ :fidelity 0.999)
       (rx pi _ :fidelity 0.98)
       (rx -pi _ :fidelity 0.98)
       (rx pi/2 _ :fidelity 0.98)
       (rx -pi/2 _ :fidelity 0.98))
      (0-1
       (cz 0 1 :fidelity 0.99)))
```

where the underscore (`_`) is a stand-in for a concrete value that matches anything.

Alternatively, providing (defaults) to the qcomplex will fill in some default gates:

  - 1Q: MEASURE, {RZ(alpha) | alpha ∈ [0, 2π)}, {RX(beta) | beta ∈ {0, ±π/2, ±π}}

  - 2Q: CZ

The above becomes
```
    (chip "humber road chippy"
      (0 (defaults))
      (1 (defaults))
      (0-1 (defaults)))
```

2021-01-28 16:06 UTC, notmgsk commented on src/chip/builder.lisp
> +(defmacro chip (name &body isa)
Not my cleanest code, but I was tired?

2021-01-29 17:05 UTC, ecpeterson reviewed
Seems fine to me, except that it’s a macro, which is a little weird. Would it be so different to quote the input description? Maybe it makes handling pi/2 a little grosser?

2021-01-29 21:17 UTC, stylewarning requested changes
Overall I feel that this macro in its current state scratches a very specific itch for a very specific case of what quilc is currently capable of. In particular, I find a mixture of defaults (implicit and explicit), device non-agnosticism, and hardcoding of certain gates we currently "accept" in quilc (with no linkage or mention as to how those were specifically derived).

I definitely support easier ways to build chips. Can we make it even easier? Can we nix the whole `(0 ...)` and `(1 ...)` and `(0-1 ...)` stuff and maybe try to infer those from a flat list of gates? Maybe one can write `(rx pi/2 _)` to literally mean "RX(pi/2) anywhere on the chip". Just some thoughts.

2021-01-29 21:17 UTC, stylewarning commented on src/chip/builder.lisp
> +  (find #\- (string qcomplex)))
Nit: I prefer `(and (find...) t)` to make a boolean

2021-01-29 21:17 UTC, stylewarning commented on src/chip/builder.lisp
> +  (find #\- (string qcomplex)))
This could also be a bit better, for instance, `2Q?` could return NIL or the pair of values it parsed.

2021-01-29 21:17 UTC, stylewarning commented on src/chip/builder.lisp
> +    (qcomplex
qcomplex isn't a general industry term. What about qsimplex? Would @ecpeterson object to that?

2021-01-29 21:17 UTC, stylewarning commented on src/chip/builder.lisp
> +       (measure _ :fidelity 0.999)
I myself wouldn't object to using a shorter name for `:fidelity`, like `:fid` or even just `:f`, but `:fidelity` is perfectly fine

2021-01-29 21:17 UTC, stylewarning commented on src/chip/builder.lisp
> +     (instruction-constructor
it's still not really clear what an `instruction-constructor` is. How do I make a chip allowing for hadamard? just

```
(H _)
```

I assume.

2021-01-29 21:17 UTC, stylewarning commented on src/chip/builder.lisp
> +Alternatively, providing (defaults) to the qcomplex will fill in some default gates:
This is pretty Rigetti-specific.

2021-01-29 21:17 UTC, stylewarning commented on src/chip/builder.lisp
> +  `(let ((chip (make-hash-table :test #'equal))
check that NAME is of the appropriate type

2021-01-29 21:17 UTC, stylewarning commented on src/chip/builder.lisp
> +              (measure (qubit &key (fidelity 0.95) duration)
why an imperfect default?

2022-01-06 19:39 UTC, closed without merging