Teach the compiler how to compile parallel programs.
quil-lang/quilc pull request #759
Opened 2021-10-29 22:50 UTC by karlosz

Using disconnected components.

Previously, we only supported allocating qubits in the program onto
the single largest component, precluding parallel program compilation,
regardless of whether the QPU topology supports it. Fix this and use a
greedy allocation scheme allowing more classes of programs to get
compiled onto QPUs with multiple connected components.

Conceptually, this is as if we combined mutliple QPUs into a
"multi-core" system, and we are now scheduling quil programs to use
them intelligently.

Fixes issue #74.

2021-10-29 22:56 UTC, stylewarning requested changes
One bit of preliminary feedback.

2021-10-29 22:56 UTC, stylewarning commented on tests/addresser-tests.lisp
>                     (quil::chip-contiguous-subschedule-from-last-instructions
Can you add a test using two qubit gates, and another test demoing failure to compile across a connected component? (Use `signals` for the latter.)

2021-11-01 18:41 UTC, karlosz commented on tests/addresser-tests.lisp
>                     (quil::chip-contiguous-subschedule-from-last-instructions
Will do. I think I'm just going to go ahead and use the condition system more aggressively in this part of the code.

2021-11-03 18:49 UTC, stylewarning submitted a review, later dismissed
It seems good to me. But I'd like @kilimanjaro to also give a passing review too.

2021-11-03 22:30 UTC, kilimanjaro requested changes

2021-11-03 22:30 UTC, kilimanjaro commented on src/addresser/addresser-common.lisp
> +                                             (instr-used-qubits-ccs instrs)))
I think the CC assignment has to take into account the `initial-rewiring`. If provided this contains a (partial) logical -> physical qubit assignment, and so implies a corresponding (partial) assignment of logical ccs to physical ccs. I think you should add a test which evaluates the behavior of `do-greedy-temporal-addressing` directly, e.g. providing such an initial rewiring. We'd want a nice error if the rewiring is impossible to satisfy (right now, we'd get an error, but probably during the middle of addressing), and if it is possible it should be allowed.

2021-11-03 22:30 UTC, kilimanjaro commented on tests/addresser-tests.lisp
> +  (let ((program "DECLARE ro BIT[3]
Right now, these examples only exercise the `PARTIAL` initial rewiring (no assignments exist). It's probably a good idea to cook up a test using `GREEDY` and `NAIVE` as well, verifying that they behave as expected with parallel programs. `PRAGMA INITIAL_REWIRING GREEDY` etc.

2021-11-03 22:30 UTC, kilimanjaro commented on src/addresser/initial-rewiring.lisp
> +       (generate-random-rewiring n-qubits))
It might be reasonable to update this for disconnected chips. I've never used the RANDOM initial rewiring, but if we wanted it around I'd prefer that it can at least try to satisfy CC constraints (otherwise, a program using 4 qubits, running on a device with two disjoint 4-qubit components, with random initial rewiring would fail to compile something like 97% of the time just due to the initial assignment bridging the components).

2021-11-03 23:32 UTC, karlosz commented on tests/addresser-tests.lisp
> +  (let ((program "DECLARE ro BIT[3]
I think with GREEDY specifically, since it makes all the assignments, nothing bad happens since the addresser proper never needs to assign qubits, and hence it can't do anything incompatible with the connected component mapping.

2021-11-03 23:34 UTC, karlosz commented on src/addresser/addresser-common.lisp
> +                                             (instr-used-qubits-ccs instrs)))
How would such a partial rewiring get provided? Do we even want to allow the user to supply a partial rewiring? It seems hard to force the logic in non-identity cases to check and allocate the components around arbitrary qubit correspondences. Greedy simply tries to assign everything from the start, using a greedy assignment from logical to physical ccs, so this machinery never fires in the addresser proper.

2021-11-04 00:59 UTC, kilimanjaro commented on src/addresser/addresser-common.lisp
> +                                             (instr-used-qubits-ccs instrs)))
The rewiring is already provided here, in the form of the `initial-l2p` slot on the addresser state (and also the `initial-rewiring` keyword arg... not sure why we have both of these, but `compiler-hook` currently passes the same data through both of these). 

This is not necessarily user supplied; `do-greedy-addressing` gets called for blocks in the control flow graph, and so in principle the initial rewiring of one block is the final rewiring of its predecessor block. The machinery at this point should be agnostic to whatever 'rewiring strategy' is used for constructing the initial rewiring.

2021-11-04 18:39 UTC, karlosz commented on src/addresser/initial-rewiring.lisp
> +       (generate-random-rewiring n-qubits))
Do you think anyone cares if we gut the RANDOM rewiring? It doesn't make any sense to me; we already have enough in-determinism in the compiler to deal with. Was this added for a purpose or just for fun?

2021-11-04 19:53 UTC, kilimanjaro commented on src/addresser/initial-rewiring.lisp
> +       (generate-random-rewiring n-qubits))
Personally I'd be fine with gutting it. An adequate substitute (for a different PR) would be to add the option to explicitly set the initial rewiring; syntactically this might look like `PRAGMA INITIAL-REWIRING EXPLICIT "#(0 2 1 4 3)"`. This would be intended for power users, who'd be able to cook up random rewirings and attach them if so desired. Wonder what @stylewarning thinks.

2021-11-04 19:57 UTC, ecpeterson commented on src/addresser/initial-rewiring.lisp
> +       (generate-random-rewiring n-qubits))
I don't feel strongly about whether it's kept, but it was originally introduced as a benchmarking convenience: if the addresser is constrained by some garbage assignment rather than beingn able to pre-assign qubits willy-nilly, how performant is its output? Starting with a random assignment tests that pretty aggressively.

2021-11-04 21:05 UTC, karlosz commented on src/addresser/initial-rewiring.lisp
> +       (generate-random-rewiring n-qubits))
Great, that use case makes a lot more sense. It shouldn't be difficult to try and just make :random satisfy the right connected component conditions, and that machinery might be largely the same as the bookkeeping needed to implement Erik's explicit rewiring suggestion anyway (to ensure compatibility with chip ccs).

2021-11-05 23:08 UTC, karlosz commented
Updated PR to calculate the component mapping globally, making the component mapping determined together with the global initial rewiring.

2021-11-06 00:24 UTC, stylewarning commented
@karlosz is this ready for re-review?

2021-11-06 00:26 UTC, karlosz commented
Yes.

2021-11-09 21:15 UTC, kilimanjaro commented on src/addresser/initial-rewiring.lisp
> +      (error 'chip-insufficient-qubits
Although you're consistent here with the prior behavior, I'm not that I agree with it.

Considering
```
(prog-initial-rewiring (parse-quil "X 100") (build-nq-linear-chip 3))
```
we'd have an error, because `qubits-needed` returns 101 (1+ the max qubit index seen). I don't see how this is sensible behavior; in particular, the program at this point involves "logical qubits" (we haven't passed it through the addresser yet) so the numbers shouldn't mean anything at all (they should be considered more as variable names than hardware registers).

My feeling is that this should only be an error for `naive` rewirings. Note that it appears the issue has been skirted in` compiler-hook`, because it calls `compress-qubits`, which tries to relabel qubit indices starting from 0, and hence subsequent `max` calculations work just fine in most cases.

2021-11-09 21:15 UTC, kilimanjaro commented on src/addresser/initial-rewiring.lisp
> +            :do (typecase inst
I'd like to handle the `RESET <q>` case here as well, even though it probably gets dealt with implicitly because anybody resetting a qubit is likely to use it later. My advice is to not do a typecase but instead rely on a suitable generic, e.g. `(remove-if-not #'qubit-p (arguments instr))`.

2021-11-09 23:32 UTC, kilimanjaro commented on src/addresser/initial-rewiring.lisp
> +      (error 'chip-insufficient-qubits
(Also, I think for this PR it's ok if we stick with the prior behavior, instead making an issue re: this point.)

2021-11-10 04:53 UTC, karlosz commented on src/addresser/initial-rewiring.lisp
> +      (error 'chip-insufficient-qubits
I agree this behavior is weird; I did a double take when I first tried using `qubits-needed` &co. We can change this behavior later, but that can be done independently of this change, as `qubits-needed` seems to imply relabeling per se.

2021-11-10 08:19 UTC, stylewarning commented on src/addresser/initial-rewiring.lisp
> +      (error 'chip-insufficient-qubits
QUBITS-NEEDED is defined by what a "quantum abstract machine" defines as needed, so the behavior is correct.

But I could be on board with renaming that to MAXIMUM-QUBIT-PRESENT and creating a function DISTINCT-QUBITS-USED, or something.

2021-11-18 01:44 UTC, karlosz commented on src/addresser/initial-rewiring.lisp
> +      (error 'chip-insufficient-qubits
In any case, we can rename the functions later in a separate change.

2021-11-18 02:05 UTC, karlosz commented on src/addresser/initial-rewiring.lisp
> +            :do (typecase inst
Hm, I'm pretty sure the way I do it here matches the old behavior when groveling for live qubit dependencies in the program. Plus, I tried doing it the way you said and I think that actually breaks the measurement tests, since `arguments` doesn't actually correspond to what is needed. (PRAGMA doesn't even have a method defined for it.)

2021-11-18 21:07 UTC, kilimanjaro commented on src/addresser/initial-rewiring.lisp
> +            :do (typecase inst
Well, regardless of whether it's done with an explicit typecase or a suitable generic, we should handle every instruction involving qubit arguments. What's missing here is a case for `reset-qubit`. I'd say that the previous implementation was just wrong, but we don't use the `RESET <q>` instruction very often, and even then we usually do something with the qubit afterwards, so it just slipped under our radar.

2021-11-18 23:04 UTC, kilimanjaro commented on src/addresser/initial-rewiring.lisp
> +            :do (typecase inst
(And with that change, this PR looks good to me, assuming tests pass.)

2021-11-18 23:18 UTC, merged