Defgate as sequence
quil-lang/quilc pull request #785
Opened 2022-01-07 21:55 UTC by Spin1Half

Proposed implementation of defgate as sequence outlined in issue #762 

This adds syntax to Quil and rudimentary integration with the compilation pipeline.

2022-01-18 02:55 UTC, ecpeterson commented
Responding to the general RFC from the Quil stack meeting a couple weeks ago:

I very much like the spirit of this PR / extension to the Quil spec. I don't much care for DEFCIRCUIT, and I think this captures many of the parts of that which are in common use while avoiding some of the snares.

One main concern: what does the second instance of `U` mean in the following?

```
DEFGATE U q AS GATE-SEQUENCE:
    U q
```

Other `DEFGATE` instances don't suffer from this potential recursion, and I think it's legal in a DEFCIRCUIT (though the compiler's "expand" pass may complain). I believe there's something semantic to pin down here related to name resolution — which, AFAIK, is part of the compiler internals but whose behavior is not expressly prescribed at the level of the language spec.

2022-01-18 05:31 UTC, Spin1Half commented
@ecpeterson The plan right now is to consider any circularity in the definitions invalid (i.e. its fine for one defgate to depend on another, as long as there are no circular dependencies).  I have made a validation routine to identify any circular dependencies and produce an error in this case (not pushed yet, stay tuned).

2022-01-18 14:49 UTC, ecpeterson commented
Reasonable 👍, but also restrictive — my understanding from the meeting was that this was to be one way to describe “translators” to the compiler, and the quoted case is such a translator which is presently used.

Just something to think about. Should gates be permitted to have multiple compatible definitions — some potentially “self”-referencing another definition? Maybe! Sounds like a lot of work to make use of, but it could be worth consciously avoiding making the present guts deeply incompatible with such a future.

2022-01-18 20:13 UTC, stylewarning commented
I think it's a reasonable restriction if these must act as unambiguous gate *definitions*. I think the restriction could be lifted if we go in the direction of adding a keyword (eg DEFGATE blah AS ALTERNATIVE blah) or a pragma (I'm less enthusiastic) which won't install the gate as a definition, but rather as an identity to be dwelled upon. Something like ALTERNATIVE implies there was already an unambiguous definition somewhere.

2022-02-07 22:34 UTC, Spin1Half commented
I believe this PR to be *functionally* complete, so I will take it out of draft. Though I certainly expect there are spots that can be improved. Looking forward to any feedback!

2022-02-08 22:52 UTC, karlosz requested changes
My initial review. Good work.

2022-02-08 22:52 UTC, karlosz commented on src/analysis/resolve-objects.lisp
> +      ;; resolve defgate as sequence definitions
Two things: Could this map get folded into the map above?

And here, with `(cond ...)` and only one leg, the more idiomatic usage is `(when <cond> <body>)`.

2022-02-08 22:52 UTC, karlosz commented on src/analysis/validate-seq-gate.lisp
> +(defun verify-no-loops (graph &optional (path NIL))
Try to use `(cond ...)` here.

2022-02-08 22:52 UTC, karlosz commented on src/analysis/validate-seq-gate.lisp
> +(defun neighboors-of (graph key)
`neighbors`?

Also, again `(cond ...)` seems more idiomatic here.

2022-02-08 22:52 UTC, karlosz commented on src/gates.lisp
> +;;; we dont think this is neccesary because seq gate definition
Grammar/spelling.

2022-02-08 22:52 UTC, karlosz commented on src/analysis/validate-seq-gate.lisp
> +(defgeneric graph-of-seq-def (program)
So the code here to build a graph and do cyclic dependency analysis probably needs at least a comment explaining the data structure used for the graph, and potentially a test to make sure this machinery works. If the graph is only being used for loop detection, there is probably a lighter weight way of doing this by just directly doing DFS, or if we'd like to have general "call" graphs, it might be better to have a more polished interface to that.

2022-02-09 23:43 UTC, Spin1Half commented on src/analysis/validate-seq-gate.lisp
> +(defun verify-no-loops (graph &optional (path NIL))
Alternatively, one could opt for something like:
```
(cond ((and S1 S2) 
        (cond (S3 A) (t B)))
    (t Nil))
```

2022-02-09 23:44 UTC, karlosz commented on src/analysis/validate-seq-gate.lisp
> +(defun verify-no-loops (graph &optional (path NIL))
I'd rewrite the condition like this:
```(when (and graph
                         (or (null (cdr path)))
                               (first path)))
        (if path
            ...
            ...))
```
actually. But its hard to tell whats going on because its unclear how the graph is being represented. I think you'll find with a better representation the conditionalization will simplify a lot.

`WHEN` is used specifically when you are just trying to do something for its side effect, as seems to be the case here.

2022-02-10 01:10 UTC, kilimanjaro requested changes

2022-02-10 01:10 UTC, kilimanjaro commented on src/gates.lisp
> +(defun instantiate-from-formal-name (list-names lut-names)
I think this could be `(mapcar (lambda (name) (gethash (formal-name name) lut-names)) lit-names)`, and similarly for `instantiate-from-param-name`. In general, I prefer using `mapcar` rather than direct list traversal, where sensible.

2022-02-10 01:10 UTC, kilimanjaro commented on src/gates.lisp
> +          :do (setf instantiated-list (cons (instantiate-gate-application gate-app lookup-arg lookup-param) instantiated-list)))
This is another place where `mapcar` is more convenient -- no need to reverse the list, just 

```
(mapcar (lambda (gate-app) (instantiate-gate-application gate-app lookup-arg lookup-param)) 
  (sequence-gate-definition-sequence seq-gate))
```

2022-02-10 01:10 UTC, kilimanjaro commented on src/gates.lisp
> +  (setf (application-arguments gate-app) (instantiate-from-formal-name (application-arguments gate-app) lut-args))
As a tiny convenience, you can do multiple assignments in a single `setf` form, e.g.
```
(setf a 1
        b 2)
```
They will be evaluated sequentially.

2022-02-10 01:25 UTC, stylewarning commented on src/gates.lisp
> +#+ignore
I'm ok if it's `#+#:some-comment` since that can never be in `*features*`

2022-02-10 09:03 UTC, Spin1Half commented on src/gates.lisp
> +;;;; some leftover stuff from standard-gates.lisp and elsewhere
Might have gotten moved while I was working on this PR? I was confused why this showed up in the diff as well, meant to point it out.

2022-02-14 22:37 UTC, Spin1Half commented on src/gates.lisp
> +(defmethod gate-matrix ((gate sequence-gate-definition) &rest parameters)
Definitely agree, I will include this comment in the "make defgate as sequence not shamelessly unoptimized" ticket

2022-02-14 22:49 UTC, Spin1Half commented on src/gates.lisp
> +(defmethod gate-matrix ((gate sequence-gate-definition) &rest parameters)
https://github.com/quil-lang/quilc/issues/792

2022-02-17 22:53 UTC, Spin1Half commented on src/analysis/validate-seq-gate.lisp
> +(defgeneric graph-of-seq-def (program)
All done, looks much better now, way less code.

2022-02-22 20:08 UTC, karlosz commented on src/analysis/validate-seq-gate.lisp
> +  (dolist (gate-def gate-defs) (when (typep gate-def 'SEQUENCE-GATE-DEFINITION)
Idiomatic formatting for `dolist` is to have a newline before the body, i.e. before the `when`.

2022-02-22 20:09 UTC, karlosz approved these changes
Lgtm outside of one minor nit.

2022-03-15 22:35 UTC, stylewarning requested changes
I think the biggest change is to do a backpedal and introduce a new gate class.

2022-03-15 22:35 UTC, stylewarning commented on cl-quil.asd
> +                             (:file "validate-seq-gate")))))
can you spell out `sequence-gate`? and `git mv` the file to the new name

2022-03-15 22:35 UTC, stylewarning commented on src/analysis/resolve-objects.lisp
> +                       (let ((*in-definition-body* t))
indentation looks wrong on github; please verify this gets indented correctly.

2022-03-15 22:35 UTC, stylewarning commented on src/analysis/validate-seq-gate.lisp
> +                  (quil-parse-error "argument cannot be qubit"))
> argument of blah-blah cannot be qubit

2022-03-15 22:35 UTC, stylewarning commented on src/analysis/validate-seq-gate.lisp
> +                  (quil-parse-error "argument is not formal"))
same here, improve error message

2022-03-15 22:35 UTC, stylewarning commented on src/analysis/validate-seq-gate.lisp
> +                 (T T))))
lowercase `t`'s

2022-03-15 22:35 UTC, stylewarning commented on src/analysis/validate-seq-gate.lisp
> +                  (quil-parse-error "argument ~a is not in gatedef arguments" arg))
spell out, use full english words

2022-03-15 22:35 UTC, stylewarning commented on src/analysis/validate-seq-gate.lisp
> +    (when (typep gate-def 'SEQUENCE-GATE-DEFINITION)
lowercase class name

2022-03-15 22:35 UTC, stylewarning commented on src/analysis/validate-seq-gate.lisp
> +            (quil-parse-error (format nil "Defgate sequence dependencies contains a loop: ~a " (reverse (cons gate-name ancestors))))
`DEFGATE AS SEQUENCE`

2022-03-15 22:35 UTC, stylewarning commented on src/gates.lisp
> +;;; SEQUENCE GATE
I've changed my mind about this. I do think you should make something called `sequence-gate` which just has a single field containing the sequence gate definition, and nothing else.

In retrospect I think punning a definition as a gate will be too confusing to maintain and debug in the future.

2022-03-15 22:35 UTC, stylewarning commented on src/gates.lisp
> +  (let* (
no newline

2022-03-15 22:35 UTC, stylewarning commented on src/parser.lisp
> +              :name name :parameters params :arguments args :sequence parsed-body :context context)
put keyword args on newlines

2022-03-15 23:41 UTC, Spin1Half commented on src/gates.lisp
> +;;; SEQUENCE GATE
I've pushed some new changes up that try to flush out the sequence-gate class slightly more than just putting a sequence gate definition inside.  Let me know if that looks okay, or if doing it this way has problems, I'm happy to revert back to the original suggestion instead.

2022-03-16 22:39 UTC, Spin1Half commented on src/gates.lisp
> +;;; SEQUENCE GATE
I believe this has been implemented now, but you will want to check my most recent commit and make sure that I correctly interpreted what you were asking for.

2022-03-17 23:32 UTC, stylewarning commented on src/analysis/validate-sequence-gate.lisp
> +                  (sequence-gate-definition-sequence gate-def))))
```
(defun neighbors-of-sequence-gate-def (gate-def)
  "Returns all sequence gate defs that another sequence gate def depends on."
  (mapcan (lambda (x)
            (let ((g (gate-application-gate x)))
              (if (not (typep g 'sequence-gate))
                  nil
                  (list (sequence-gate-gate-definition g)))))
          (sequence-gate-definition-sequence gate-def)))
```

2022-03-17 23:34 UTC, stylewarning commented on src/cl-quil.lisp
> +  '(expand-circuits type-check simplify-arithmetic validate-defgate-loops)
put validation at the start

2022-03-17 23:35 UTC, stylewarning commented on src/analysis/validate-sequence-gate.lisp
> +(define-transform validate-defgate-loops (validate-defgate-loops)
depend on process-includes

2022-03-17 23:37 UTC, stylewarning commented on src/ast.lisp
> +      (format stream "    ~a~%" (print-instruction-to-string operation))))
```
(format stream "    ~/quil:instruction-fmt/~%" operation)
```

2022-03-17 23:37 UTC, stylewarning commented on src/gates.lisp
> +;;;
delete extra ;;;

2022-03-17 23:38 UTC, stylewarning commented on src/gates.lisp
> +;;;
delete whole comment

2022-03-17 23:38 UTC, stylewarning commented on src/gates.lisp
> +                 :reader sequence-gate-gate-definition)))
write a doc string, note that there's no practical difference between a sequence gate definition and a sequence gate itself

2022-03-17 23:41 UTC, stylewarning commented on src/gates.lisp
> +  (let ((n (length (sequence-gate-definition-arguments (sequence-gate-gate-definition gate)))))
gate-definition-qubits-needed

2022-03-18 20:17 UTC, stylewarning approved these changes

2022-03-18 20:18 UTC, merged