print warning when there are ambiguous gatedefs or circuitdefs by def…
quil-lang/quilc pull request #807
Opened 2022-03-24 22:04 UTC by Spin1Half

change default behavior to print a warning when there are ambiguous gate definitions or circuit definitions

2022-03-29 23:52 UTC, stylewarning commented
I would change to emitting a `style-warning` instead of a full warning. You could make a new condition class for this, or just use `alexandria:simple-style-warning`.

That should fix the tests.

2022-03-30 00:00 UTC, karlosz requested changes

2022-03-30 00:00 UTC, karlosz commented on src/cl-quil.lisp
> +      (gate-definition (alexandria:simple-style-warning (format nil "Gate ~A has multiple definitions, this leads to ambiguous behavior.~%" (gate-definition-name instr))))
You don't need to write `(format nil ...)` here. `warn` already can deal with a format string and format arguments by itself.

2022-03-30 00:00 UTC, karlosz commented on src/cl-quil.lisp
> +      (circuit-definition (alexandria:simple-style-warning (format nil "Circuit ~A has multiple definitions, this leads to ambiguous behavior.~%" (circuit-definition-name instr)))))
Ditto.

2022-03-30 00:00 UTC, Spin1Half commented on src/cl-quil.lisp
> +      (gate-definition (alexandria:simple-style-warning (format nil "Gate ~A has multiple definitions, this leads to ambiguous behavior.~%" (gate-definition-name instr))))
good point!

2022-03-30 00:07 UTC, karlosz submitted a review, later dismissed

2022-03-30 00:08 UTC, stylewarning requested changes

2022-03-30 00:08 UTC, stylewarning commented on src/cl-quil.lisp
> +    (typecase instr
either make this an `etypecase` or print a diagnostic in a `t` branch

2022-03-30 00:11 UTC, stylewarning approved these changes

2022-03-30 01:39 UTC, merged