Rework some of the standard gates init logic to accommodate seq gates
quil-lang/quilc pull request #809
Opened 2022-04-06 23:20 UTC by Spin1Half

2022-04-08 22:28 UTC, stylewarning requested changes

2022-04-08 22:28 UTC, stylewarning commented on src/initialize-standard-gates.lisp
> +  (let ((stdgates-file (asdf:system-relative-pathname
I would wrap in `(unless (boundp'**default-gate-definitions**) ...`

2022-04-08 22:28 UTC, stylewarning commented on src/initialize-standard-gates.lisp
> +              (dolist (gate-def (read-standard-gates-from-file) table)
it doesn't look like we are actually passing the file name to this

2022-04-08 22:28 UTC, stylewarning commented on src/initialize-standard-gates.lisp
> +            (let ((table (make-hash-table :Test 'equal)))
lowercase `test`

2022-04-08 22:28 UTC, stylewarning commented on src/gates.lisp
> +    (parsed-program-gate-definitions parsed-program)))
I would move this to the initialize file

2022-04-08 22:28 UTC, stylewarning commented on src/gates.lisp
> +(declaim (ftype function resolve-objects))
you'll be able to delete this

2022-04-08 22:28 UTC, stylewarning commented on src/gates.lisp
> +(defvar **default-gate-definitions**)
I would add a comment above this saying what it is and where it's getting initialized.

2022-04-21 21:27 UTC, Spin1Half commented
This was in draft because of issues I was encountering for an unrelated reason, I will address these issues in a separate PR

2022-04-21 23:07 UTC, stylewarning requested changes

2022-04-21 23:07 UTC, stylewarning commented on src/initialize-standard-gates.lisp
> +  (eval-when (:compile-toplevel :load-toplevel :execute)
I think this eval-when needs to be on the outside

also please write a comment above this block of code to explain what it's doing anx why it's here. It's unusual to see toplevel code getting evaluated like this.

Lastly, I would wrap this stuff in a function itself, and do the eval-when stuff around a call to it.

```
(eval-when (...)
  (defun read-standard...)

  (defun initialize-standard-gate-definitions...)

  (initialize-standard-gate-definitions)

)  ; eval-when
```

2022-04-22 01:03 UTC, Spin1Half commented on src/initialize-standard-gates.lisp
> +  (eval-when (:compile-toplevel :load-toplevel :execute)
Implemented the structural changes.

Did my best to explain what was going on, but I don't know that I was as informative as I could be

2022-04-22 22:42 UTC, stylewarning commented on src/initialize-standard-gates.lisp
> +  (initialize-standard-gates));eval-when
```suggestion
  (initialize-standard-gates)
) ; eval-when
```

2022-04-22 22:57 UTC, merged