Add Clifford+T compiler
quil-lang/quilc pull request #819
Opened 2022-05-20 23:04 UTC by aijony

2022-05-23 22:56 UTC, eliaslfox commented on src/discrete/numeric/naturals.lisp
> +  (define-type Z Z)
`(repr :enum)`

2022-05-23 22:56 UTC, eliaslfox commented on src/discrete/numeric/naturals.lisp
> +  ;; (repr :transparent)
Is there a reason this is commented out?

2022-05-23 22:56 UTC, eliaslfox commented on src/discrete/operators/ma-normal-form.lisp
> +  (define-type LeftMAForm
`(repr :enum)`

2022-05-23 22:56 UTC, eliaslfox commented on src/discrete/operators/ma-normal-form.lisp
> +  (define-type MidMAForm
`(repr :enum)`

2022-05-23 22:56 UTC, eliaslfox commented on src/discrete/operators/rz.lisp
> +  (define-type (Rz :a)
`(repr :transparent)`

2022-05-23 22:56 UTC, eliaslfox commented on src/discrete/operators/utilities.lisp
> +(coalton-toplevel
Should `Backwards` be upstreamed?

2022-05-23 22:56 UTC, eliaslfox commented on src/discrete/numeric/circle.lisp
> +  (define-type RootUnity8
`(repr :transparent)`

2022-05-23 22:56 UTC, eliaslfox commented on src/discrete/numeric/circle.lisp
> +  (define-type RootUnity4
`(repr :transparent)`

2022-05-24 02:18 UTC, stylewarning requested changes
I'm about 1/3 of the way through. I do plan on doing a couple passes and at least one complete review.

Some general comments:

- I'd like to see more toplevel documentation at the top of each file. What's the file's purpose? It's ok to be brief, as long as the reader can get a sense of what's going on.
- I'd like a README added to the src/disctete directory briefly describing the layout, what to expect to find where, and any gotchas about building.
- I'd like some documentation added to the toplevel README, especially about how to build/use/load this software. (See the section on POST_LOAD_blahblah whatever the variable is called.)

2022-05-24 02:18 UTC, stylewarning commented on src/discrete/numeric/utilities.lisp
> +       (define (toRational x)
indentation

2022-05-25 01:39 UTC, aijony commented on src/discrete/compilers/clifford-t.lisp
> +  ;; Y = H.S.Z.X.S.H
Whoops, I forgot to throw away phase - I'll change that to Y = Z X

2022-05-25 01:40 UTC, aijony commented on src/discrete/discrete-common.lisp
> +(defparameter *deterministic-approximation* t
On second thought, I will get rid of it. The paper calls for "random" numbers for seeding, but I will just do psuedo-random.

2022-05-25 01:41 UTC, aijony commented on app/src/entry-point.lisp
> +    ("8Q-cliffordt" (funcall (alexandria::find-symbol
Is there a better way to do this?

2022-05-25 02:07 UTC, ecpeterson commented
Just wanted to drop by to say that this PR is _extremely_ cool for a whole spread of reasons. Really excellent work.

2022-05-25 02:31 UTC, stylewarning commented on app/src/entry-point.lisp
> +    ("8Q-cliffordt" (funcall (alexandria::find-symbol
We could make this into a hash table (as a part of a *separate* system) and add to the hash table elsewhere. We could leave this chip spec off in this PR and implement that in a separate PR.

2022-07-22 20:14 UTC, stylewarning approved these changes

2022-07-22 20:14 UTC, merged