Improve error for unrecognized instructions
quil-lang/quilc pull request #866
Opened 2023-01-12 16:12 UTC by randall-fulton

2023-01-19 19:53 UTC, stylewarning requested changes
nit: I think the condition should be exported

There are probably other places where this condition could be signaled. Have you done a quick scan through to see where it might be applicable? (I'm fine not being totally comprehensive in the first PR.)

Otherwise, this is a great idea and good addition. Thanks!

2023-01-30 16:47 UTC, randall-fulton commented
@stylewarning Sorry for the delay. Had a nice little Covid battle there in the middle.

The condition is exported now. I've attempted to find any other obvious usages of the new condition, but am admittedly pretty unfamiliar with `quilc`, so it's more than possible I'm missing something. If you had anything specific in mind, let me know and I can make the change to introduce this condition.

2023-02-01 19:38 UTC, stylewarning requested changes
one tiny thing, then we are good to go!

2023-02-01 19:38 UTC, stylewarning commented on src/addresser/initial-rewiring.lisp
> +                     (when (zerop (list-length inst-arguments))
zerop list-length => endp

It's small but it changes it from linear to constant time.

2023-02-02 14:02 UTC, randall-fulton commented on src/addresser/initial-rewiring.lisp
> +                     (when (zerop (list-length inst-arguments))
Wonderful little nugget of knowledge. I'll remember that one.

2023-02-02 15:00 UTC, notmgsk requested changes

2023-02-02 15:43 UTC, randall-fulton commented on tests/addresser-tests.lisp
> +  (let ((program (safely-parse-quil "a"))
👀 Oh no

2023-02-03 00:52 UTC, stylewarning approved these changes

2023-02-06 11:50 UTC, notmgsk approved these changes

2023-02-06 11:50 UTC, notmgsk commented
Thanks, @randall-fulton :D

2023-02-06 11:50 UTC, merged

2023-02-06 13:46 UTC, randall-fulton commented
Thank you both for the feedback.