Add Extern Pragma and Support
quil-lang/quilc pull request #880
Opened 2023-03-15 23:32 UTC by macrologist

The EXTERN Pragma allows for users to indicate that certain operators should be "virtual" from the perspective of the frontend parsing and compilation stages. By virtual, I mean that applications of these operators do not have a definition.

It is expected that users will provide definition for these externs during `backend-compile` for their own subclasses of `cl-quil:backend`.   

For example:

```
PRAGMA EXTERN PHONY

X 0
CNOT 1 0
PHONY 1
CNOT 0 1
```

The above code will parse and compile but result in an opaque instance of `extern-application` in the resulting code. Extern instructions may be rewired, but will otherwise remain untouched. Similar to the effect of `PRESERVE_BLOCK` pragmas.

Addtionally, the user can specify that an ordinarily "off the shelf" gate should be an EXTERN, meaning that, again, the user is expected to supply an implementation for that gate on the backend.

E.g. 

``` 
PRAGMA EXTERN H
PRAGMA EXTERN CNOT

X 0
CNOT 1 0
Y 0
H 1
CZ 1 0
```

Such a program will not allow the compiler to neither optimize or nativize `CNOT` and `H` gate applications.

2023-03-16 00:17 UTC, stylewarning requested changes
Overall looking good. One thing I'm wondering is whether this should be a pragma or new keyword. Given it's newness, I'm fine with keeping it a pragma for now, but given the attitude I have toward programs (remove them to keep a valid program), they're a bit of an odd duck. I'm not intent on getting to bikesheddy about it now though. 

Make sure that a compiled program still maintains the EXTERN pragmas.

2023-03-16 00:17 UTC, stylewarning commented on src/ast.lisp
> +The intent is to allow users to supply definitions to these operations in a form that comports with their compilation target., but to still be able to refer to these operations in their Quil source c
stray period

I would also reference PRAGMA PRESERVE_BLOCK, and to prefer to use that in the appropriate circumstance.

2023-03-16 00:17 UTC, stylewarning commented on src/ast.lisp
> +  (:documentation "Represents an externed operation. An extern is expected to receive its definition late in the compilation process, mostly likely for a specialization of cl-quil:backend-compile.
Add to the docs that this, like UNRESOLVED-APPLICATION, is a tool for users to compile programs usually beyond the Quil level. These application classes don't in and of themselves carry meaningful semantics with respect to the quantum abstract machine (i.e., they can't be executed or simulated).

2023-03-16 00:17 UTC, stylewarning commented on src/ast.lisp
> +   (externed-operations :initarg :externed-operations
Do you think "extern-operations" is better for consistency?

2023-03-16 00:17 UTC, stylewarning commented on src/cfg.lisp
> +  ;; extern applications should be preserved from nativization and optimization
I only have hazy memory of the mechanics of this function, but is this going to inadvertently preserve all other instructions resident to this block too? Should extern instructions be pushed to their own block? Or maybe no preserve-blocks at all?

2023-03-16 00:17 UTC, stylewarning commented on tests/extern-pragma-tests.lisp
> +(deftest test-extern-pragmas ()
add a test that something like

    PRAGMA EXTERN H
    H 0
    Y 0

to see that H stays externed and doesn't compile further, but Y does.

2023-03-16 00:30 UTC, macrologist commented on src/cfg.lisp
> +  ;; extern applications should be preserved from nativization and optimization
I wasn't totally sure about this: I'd hoped compilation tests would reveal issues. I'll add more tests and report back.

2023-03-17 01:51 UTC, macrologist commented
@stylewarning I have taken your idea about the keyword approach to heart. As of 1481149 the pragma has been removed and replaced with a new keyword.

2023-03-17 07:05 UTC, stylewarning requested changes
Add some parser tests to the right place too; you'll need to spelunk to see how they're done now

2023-03-17 07:05 UTC, stylewarning commented on src/ast.lisp
> +         :documentation "The Name of the operation being marked as an EXTERN"))
lower n

2023-03-17 07:05 UTC, stylewarning commented on src/ast.lisp
> +(defclass extern-operation ()
i would call it a directive (or just EXTERN): https://quil-lang.github.io/#3-3Main-Program-Elements

2023-03-17 07:05 UTC, stylewarning commented on src/ast.lisp
> +   :extern-operations (make-hash-table :test #'equal))
here, OPERATION is OK i think

2023-03-17 07:05 UTC, stylewarning commented on src/package.lisp
> +   #:extern-application                 ; CLASS
export the AST node too

2023-03-17 19:32 UTC, stylewarning approved these changes
LGTM; we'll experiment with this feature. If it's ultimately blessed as useful over the next 6 months or so, we'll standardize it in Quil.

At some point we'll need to update the QVM too.

2023-03-17 19:32 UTC, stylewarning commented on src/compiler-hook.lisp
> +          ;; retain the old circuit and gate  definitions
double spacer

2023-03-17 19:32 UTC, merged

2023-03-17 19:37 UTC, macrologist commented on src/compiler-hook.lisp
> +          ;; retain the old circuit and gate  definitions
fudge 😓