Refactor LIST-AVAILABLE-BACKENDS; include backend subclass trees
quil-lang/quilc pull request #881
Opened 2023-03-16 18:07 UTC by macrologist

2023-03-16 19:06 UTC, stylewarning requested changes
just very minor stylistic patterns to be consistent elsewhere

2023-03-16 19:06 UTC, stylewarning commented on src/backends/common.lisp
> +  (let ((backends))
minor nit: since the value of backends is used prior to any SETF or other explicit initialization, we should supply an initial value here of NIL.

If OTOH backends were

    ;; complicated computation to derive foo
    (setf backends foo)

then I think

    (let (backends ...)

would be ok.

2023-03-16 19:06 UTC, stylewarning commented on src/backends/common.lisp
> +                 (when direct
minor nit: prefer COND here since

1. we depend on the return value 
2. the branches have side-effectful ops

2023-03-16 22:03 UTC, macrologist commented on src/backends/common.lisp
> +                 (when direct
I altered the implementation to not depend on the return value.

2023-03-17 06:51 UTC, stylewarning submitted a review, later dismissed
i can squash merge or you can rebase first, at your preference

2023-03-17 06:51 UTC, stylewarning commented on src/backends/common.lisp
> +      (remove-duplicates backends :test #'eq))))
all this NCONCing to not end with DELETE-DUPLICATES?

2023-03-17 19:26 UTC, stylewarning approved these changes

2023-03-17 19:27 UTC, merged